#!/bin/sh

set -e

PACKAGE=wmbeacons

case "$1" in
    configure)

        # Create user if it doesn`t exist.
        if ! id $PACKAGE > /dev/null 2>&1 ; then
            adduser --system --home /srv/$PACKAGE --no-create-home \
                --ingroup $PACKAGE --disabled-password --shell /bin/bash \
                $PACKAGE
        fi

        # Make sure user owns home directory
        chown -R $PACKAGE:$PACKAGE /srv/$PACKAGE

        # Create log directory
        if [ ! -e /var/log/$PACKAGE ]; then
            mkdir /var/log/$PACKAGE
            chown -R $PACKAGE:$PACKAGE /var/log/$PACKAGE
        fi

        # Create config directory
        if [ ! -e /etc/$PACKAGE ]; then
            mkdir /etc/$PACKAGE
            chown -R $PACKAGE:$PACKAGE /etc/$PACKAGE
        fi

        # Install web application as service
        update-rc.d -f $PACKAGE defaults

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument: $1" >&2
        exit 1
    ;;
esac

exit 0
